# Generated by Django 3.0.5 on 2021-09-25 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20210922_1404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopingcart',
            options={'verbose_name_plural': 'Рецепты в корзине'},
        ),
        migrations.AlterField(
            model_name='recipes',
            name='cooking_time',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0.001, 'Время приготовления должно быть положительным числом')], verbose_name='Время приготовления, мин'),
        ),
    ]
